name: phoviz_ultimate
channels:
    - conda-forge
dependencies:
    - python=3.9
    - pip
    # Computation
    # - numpy>=1.20.*
    # - scipy>=1.7.*
    - numpy
    - scipy
    - pandas
    - pandas-flavor
    # - numba=0.55.*
    # - pingouin
    - easydict
    - ruamel.yaml
    # - pingouin
    # - cupy # must be disabled on mac
    - param
    - joblib
    # - scikit-learn
    # - hmmlearn
    - h5py
    - hdf5storage
    - pillow
    - opencv
    - openmp
    - click
    - ipython
    # # These modules are for importing DeepLabCut data, comment out if you don't need.
    # - easydict
    # - ruamel.yaml
    # - pingouin
    # - cupy  # uncomment this if you want to run correlograms with a GPU using the ccg_gpu.py module.
    # mamba install scikit-learn hmmlearn joblib pytables tqdm
    # mamba install pingouin cupy ruamel.yaml easydict pingouin cupy ruamel.yaml easydict
    - ipykernel
    - pyscaffold
    - pyscaffoldext-dsproject
    - tox
    # Visualization
    - seaborn
    - colorcet
    - pymc
    - pyvista
    - vaex
    - ipywidgets
    - matplotlib
    - ipympl # interactive matplotlib plots
    - ipygany
    - ipyvolume
    - ipyvtklink
    - panel
    - pytables
    - tqdm
    - bqplot
    - pyvista
    - vispy
    # QT
    - pyvistaqt
    - pyqtconsole
    - pyqtgraph
    - qtmodern
    - jupyter-rfb
    - pytest
    - pytest-cov
    - pyopengl
    # Works well in RedHat8. Note you may have to comment out the following lines and then install manually "pip install scikit-posthocs" in Windows.
    - pip:
        - pyqt6
        - pyqt6-tools
        - scikit-posthocs

