[tool.poetry]
name = "spike3d"
version = "0.1.1"
description = "Primary 3D Analysis Package"
authors = ["Pho Hale <halechr@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numba = "^0.56.4"
pyvista = "^0.36.1"
pyvistaqt = "^0.9.0"
loguru = "^0.6.0" # required for mpl-multitab
pyopengl = "^3.1.6"
qtawesome = "^1.2.2"
wrapt = "1.11.2"
mpl-multitab = {git = "https://github.com/CommanderPho/mpl-multitab.git"} # poetry add git+https://github.com/CommanderPho/mpl-multitab.git
ansi2html = {git = "https://github.com/CommanderPho/ansi2html.git"} # poetry add git+https://github.com/CommanderPho/ansi2html.git
vedo = {git = "https://github.com/CommanderPho/vedo.git", rev = "release/pho-working"} # poetry add git+https://github.com/CommanderPho/vedo.git#release/pho-working
pybursts = {git = "https://github.com/CommanderPho/pybursts.git"}
qdarkstyle = "^3.1"
hdf5plugin = "^4.1.1"
mplcursors = "^0.5.2"
pyqt-custom-titlebar-window = "^0.0.50"
pyqt5custom = "^1.0.1"
matplotlib = "^3.7.0"
numexpr = "^2.8.4"
scipy = "^1.10.1"
python-picard = "^0.7"
dill = {version="==0.3.5.1", extras=["graph"]} #objgraph diagnostic tool
qtconsole = "^5.4.0"
ipython = "^8.11.0"
deeptime = "^0.4.4"
attrs = "^22.2.0"
# modin = {extras = ["all"], version = "^0.18.1"} # not fully used, didn't work
# pandarallel = "^1.6.4" # not fully used, didn't work
# lead-lag = "^2.3" # didn't work
jupyterlab-lsp = "^4.0.0"

[tool.poetry.group.dev.dependencies]
pip = "^23.0"
ipython = "^8.9.0"
viztracer = "^0.15.6"
psgdemos = "^1.12.1"
pylint = "^2.16.2"
graphviz = "^0.20.1"
pydot = "^1.4.2"
pycallgraph2 = "^1.1.3"
ipykernel = "^6.21.2"
jupyterlab = "^3.6.1"
dvc = {version = "^2.45.1", extras = ["gdrive"]}
cookiecutter = "^2.1.1"
pydict2class = "^0.0.1"

[tool.poetry.group.example.dependencies]
silx = "^1.1.2"

[tool.poetry.group.remote.dependencies]
neuropy = {path = "../NeuroPy", develop=true} # , extras = ["acceleration"]
pyphocorehelpers = {path = "../pyPhoCoreHelpers", develop=true}
pyphoplacecellanalysis = {path = "../pyPhoPlaceCellAnalysis", develop=true}

# [tool.poetry.scripts]
# setup_dependent_repos = 'scripts.console:run'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
