[tool.poetry]
name = "spike3d"
version = "0.1.1"
description = "Primary 3D Analysis Package"
authors = ["Pho Hale <halechr@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numba = "^0.56.4"
pyvista = "^0.36.1"
pyvistaqt = "^0.9.0"
loguru = "^0.6.0" # required for mpl-multitab
pyopengl = "^3.1.6"
qtawesome = "^1.2.2"
wrapt = "1.11.2"
mpl-multitab = {git = "https://github.com/CommanderPho/mpl-multitab.git"} # poetry add git+https://github.com/CommanderPho/mpl-multitab.git
ansi2html = {git = "https://github.com/CommanderPho/ansi2html.git"} # poetry add git+https://github.com/CommanderPho/ansi2html.git
vedo = {git = "https://github.com/CommanderPho/vedo.git", rev = "release/pho-working"} # poetry add git+https://github.com/CommanderPho/vedo.git#release/pho-working
# pyqode-core = "^2.12.1" # https://github.com/CommanderPho/pyqode.python.git
# haesleinhuepf-pyqode.core = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# pho-pyqode-core = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# pho-pyqode-python = {git = "https://github.com/CommanderPho/pyqode.python.git"} # to fix: AttributeError: module 'pyflakes.messages' has no attribute 'ReturnWithArgsInsideGenerator'
# "pho-pyqode-core" = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# "pyqode.python" = {git = "https://github.com/CommanderPho/pyqode.python.git"} # to fix: AttributeError: module 'pyflakes.messages' has no attribute 'ReturnWithArgsInsideGenerator'
# no-poetry
# "pyqode.python" = {git = "https://github.com/CommanderPho/pyqode.python.git", rev = "no-poetry"}
# poetry add git+https://github.com/CommanderPho/pyqode.python.git#no-poetry
# pyqode-python = "^2.12.1"
# pyqode-json = "^2.10.0"
pybursts = {git = "https://github.com/CommanderPho/pybursts.git"}
qdarkstyle = "^3.1"
hdf5plugin = "^4.1.1"
mplcursors = "^0.5.2"
pyqt-custom-titlebar-window = "^0.0.50"
pyqt5custom = "^1.0.1"
matplotlib = "^3.7.0"
numexpr = "^2.8.4"
scipy = "^1.10.1"
python-picard = "^0.7"
dill = {version="==0.3.5.1", extras=["graph"]} #objgraph diagnostic tool

[tool.poetry.group.dev.dependencies]
pip = "^23.0"
ipython = "^8.9.0"
viztracer = "^0.15.6"
psgdemos = "^1.12.1"

# [tool.poetry.group.remote.dependencies]
# pyphocorehelpers = {git = "https://github.com/CommanderPho/pyPhoCoreHelpers.git"}
# neuropy = {git = "https://github.com/CommanderPho/NeuroPy.git"} # , rev = "main", extras = ["acceleration"]
# pyphoplacecellanalysis = {git = "https://github.com/CommanderPho/pyPhoPlaceCellAnalysis.git", develop=true}

[tool.poetry.group.local.dependencies]
neuropy = {path = "../NeuroPy", develop=true} # , extras = ["acceleration"]
pyphocorehelpers = {path = "../pyPhoCoreHelpers", develop=true}
pyphoplacecellanalysis = {path = "../pyPhoPlaceCellAnalysis", develop=true}
# dill = {path = "../ExternalTesting/dill", develop=true, extras=["graph"]} #objgraph diagnostic tool


[tool.poetry.group.example.dependencies]
silx = "^1.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
