[tool.poetry]
name = "spike3d"
version = "0.1.1"
description = "Primary 3D Analysis Package"
authors = ["Pho Hale <halechr@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
# pyphocorehelpers = {path = "C:/Users/pho/repos/pyPhoCoreHelpers"}
# neuropy = {path = "C:/Users/pho/repos/NeuroPy"}
# pyphoplacecellanalysis = {path = "C:/Users/pho/repos/pyPhoPlaceCellAnalysis"}
numba = "^0.56.4"
neuropy = {git = "https://github.com/CommanderPho/NeuroPy.git"} # , rev = "main", extras = ["acceleration"]
pyphoplacecellanalysis = {git = "https://github.com/CommanderPho/pyPhoPlaceCellAnalysis.git"}
pybursts = "^0.1.1"
pyvista = "^0.36.1"
pyvistaqt = "^0.9.0"
loguru = "^0.6.0" # required for mpl-multitab
pyopengl = "^3.1.6"
qtawesome = "^1.2.2"
wrapt = "1.11.2"
mpl-multitab = {git = "https://github.com/CommanderPho/mpl-multitab.git"} # poetry add git+https://github.com/CommanderPho/mpl-multitab.git
ansi2html = {git = "https://github.com/CommanderPho/ansi2html.git"} # poetry add git+https://github.com/CommanderPho/ansi2html.git
vedo = {git = "https://github.com/CommanderPho/vedo.git", rev = "release/pho-working"} # poetry add git+https://github.com/CommanderPho/vedo.git#release/pho-working
# pyqode-core = "^2.12.1" # https://github.com/CommanderPho/pyqode.python.git
# haesleinhuepf-pyqode.core = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# pho-pyqode-core = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# pho-pyqode-python = {git = "https://github.com/CommanderPho/pyqode.python.git"} # to fix: AttributeError: module 'pyflakes.messages' has no attribute 'ReturnWithArgsInsideGenerator'
# "pho-pyqode-core" = {git = "https://github.com/CommanderPho/pyqode.core.git"}
# "pyqode.python" = {git = "https://github.com/CommanderPho/pyqode.python.git"} # to fix: AttributeError: module 'pyflakes.messages' has no attribute 'ReturnWithArgsInsideGenerator'
# no-poetry
# poetry add git+https://github.com/CommanderPho/pyqode.python.git#no-poetry
# pyqode-python = "^2.12.1"
# pyqode-json = "^2.10.0"

[tool.poetry.group.dev.dependencies]
pip = "^23.0"
ipython = "^8.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
