[tool.poetry]
name = "spike3d"
version = "0.1.1"
description = "Primary 3D Analysis Package"
authors = ["Pho Hale <halechr@umich.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
# pyphocorehelpers = {path = "C:/Users/pho/repos/pyPhoCoreHelpers"}
# neuropy = {path = "C:/Users/pho/repos/NeuroPy"}
# pyphoplacecellanalysis = {path = "C:/Users/pho/repos/pyPhoPlaceCellAnalysis"}
numba = "^0.56.4"
neuropy = {git = "https://github.com/CommanderPho/NeuroPy.git"}
pyphoplacecellanalysis = {git = "https://github.com/CommanderPho/pyPhoPlaceCellAnalysis.git"}
pybursts = "^0.1.1"
# pyvista = "^0.38.1"
pyvista = "^0.36.1"
vedo = "^2023.4.3"
pyvistaqt = "^0.9.0"
mpl-multitab = "^0.0.1"
loguru = "^0.6.0" # required for mpl-multitab
pyopengl = "^3.1.6"
qtawesome = "^1.2.2"
haesleinhuepf-pyqode-python = "^2.15.2"

[tool.poetry.group.dev.dependencies]
pip = "^23.0"
ipython = "^8.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
