# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:
  build-real:
    docker:
      - image: quay.io/fenicsproject/dolfinx:dev-env-real
    environment:
      MPLBACKEND: "agg"
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - checkout

      - run:
          name: install vtkplotter
          command: |
            pip3 install vtk
            pip3 install trimesh
            pip3 install meshio
            pip3 install .

      # FEniCS:
      - run:
          name: Get dolfinx cmake compile and install
          command: |
            pip3 install git+https://github.com/FEniCS/fiat.git --upgrade
            pip3 install git+https://github.com/FEniCS/ufl.git --upgrade
            pip3 install git+https://github.com/FEniCS/ffcx.git --upgrade
            rm -rf /usr/local/include/dolfin /usr/local/include/dolfin.h
            git clone https://github.com/FEniCS/dolfinx.git
            cd dolfinx
            mkdir -p build && cd build && cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
            ninja -j3 install
            pwd
            cd ../python
            pip3 -v install . --user

      - run:
          name: run tests
          command: |
            cd
            pwd
            ls
            python3 tests/test_clone.py
            python3 tests/test_dolfin.py

      - store_artifacts:
          path: test-reports
          destination: test-reports

workflows:
  version: 2
  build-stuff:
    jobs:
      - build-real
